[package]
name = "lazy_fields"
version = "0.1.0"
authors = ["David Spies <dnspies@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
